version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    volumes:
      - ./backend:/backend
    ports:
      - "3001:3001"

  snake:
    container_name: ticTacToe
    build:
      context: .
      dockerfile: ticTacToe/Dockerfile
    volumes:
      - ./ticTacToe:/ticTacToe
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true,
      - WATCHPACK_POLLING=true
