version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    volumes:
      - ./backend:/backend
    ports:
      - "3001:3001"
